### ISSUE TITLE
如何优化网页的打印样式？

### ISSUE THREAD

**Issue by sugarmouse** [sugarmouse/interview#52]
可以利用css 的媒体查询功能，例如：
```css
@media print {
  .box {
    border: 1px solid red;
  }
}
```

题目来自饥人谷
